module net.chesstango.search {
    exports net.chesstango.search;
    exports net.chesstango.search.visitors;
    exports net.chesstango.search.smart;
    exports net.chesstango.search.smart.sorters;
    exports net.chesstango.search.smart.sorters.comparators;
    exports net.chesstango.search.smart.alphabeta.zobrist.visitors;
    exports net.chesstango.search.smart.alphabeta.zobrist.listeners;
    exports net.chesstango.search.smart.alphabeta.zobrist.filters;
    exports net.chesstango.search.smart.alphabeta.transposition;
    exports net.chesstango.search.smart.alphabeta.transposition.visitors;
    exports net.chesstango.search.smart.alphabeta.transposition.listeners;
    exports net.chesstango.search.smart.alphabeta.transposition.filters;
    exports net.chesstango.search.smart.alphabeta.transposition.comparators;
    exports net.chesstango.search.smart.alphabeta.statistics.transposition;
    exports net.chesstango.search.smart.alphabeta.statistics.node;
    exports net.chesstango.search.smart.alphabeta.statistics.node.visitors;
    exports net.chesstango.search.smart.alphabeta.statistics.node.listeners;
    exports net.chesstango.search.smart.alphabeta.statistics.node.filters;
    exports net.chesstango.search.smart.alphabeta.statistics.evaluation;
    exports net.chesstango.search.smart.alphabeta.pv;
    exports net.chesstango.search.smart.alphabeta.pv.visitors;
    exports net.chesstango.search.smart.alphabeta.pv.listeners;
    exports net.chesstango.search.smart.alphabeta.pv.filters;
    exports net.chesstango.search.smart.alphabeta.pv.comparators;
    exports net.chesstango.search.smart.alphabeta.killermoves;
    exports net.chesstango.search.smart.alphabeta.killermoves.visitors;
    exports net.chesstango.search.smart.alphabeta.killermoves.listeners;
    exports net.chesstango.search.smart.alphabeta.killermoves.filters;
    exports net.chesstango.search.smart.alphabeta.killermoves.comparators;
    exports net.chesstango.search.smart.alphabeta.evaluator;
    exports net.chesstango.search.smart.alphabeta.evaluator.visitors;
    exports net.chesstango.search.smart.alphabeta.evaluator.listeners;
    exports net.chesstango.search.smart.alphabeta.evaluator.comparators;
    exports net.chesstango.search.smart.alphabeta.egtb;
    exports net.chesstango.search.smart.alphabeta.egtb.visitors;
    exports net.chesstango.search.smart.alphabeta.egtb.liteners;
    exports net.chesstango.search.smart.alphabeta.egtb.filters;
    exports net.chesstango.search.smart.alphabeta.debug;
    exports net.chesstango.search.smart.alphabeta.debug.visitors;
    exports net.chesstango.search.smart.alphabeta.debug.traps;
    exports net.chesstango.search.smart.alphabeta.debug.traps.predicates;
    exports net.chesstango.search.smart.alphabeta.debug.traps.actions;
    exports net.chesstango.search.smart.alphabeta.debug.model;
    exports net.chesstango.search.smart.alphabeta.debug.listeners;
    exports net.chesstango.search.smart.alphabeta.debug.filters;
    exports net.chesstango.search.smart.alphabeta;
    exports net.chesstango.search.smart.alphabeta.core.visitors;
    exports net.chesstango.search.smart.alphabeta.core.listeners;
    exports net.chesstango.search.smart.alphabeta.core.filters;
    exports net.chesstango.search.smart.alphabeta.core.filters.once;
    exports net.chesstango.search.dummy;
    exports net.chesstango.search.builders;
    exports net.chesstango.search.builders.alphabeta;

    requires net.chesstango.board;
    requires net.chesstango.evaluation;
    requires net.chesstango.gardel;
    requires com.fasterxml.jackson.databind;
    requires static lombok;

    opens net.chesstango.search.gamegraph to com.fasterxml.jackson.databind;
    exports net.chesstango.search.smart.alphabeta.evaluator.filters;
    exports net.chesstango.search.smart.alphabeta.quiescence;
}